import { VIEW_SHOW } from '../../common/constants'

export const
  VIEW_NAME = VIEW_SHOW,
  INSTANCE_SHOW = VIEW_NAME + '/INSTANCE_SHOW',
  INSTANCE_SHOW_REQUEST = VIEW_NAME + '/INSTANCE_SHOW_REQUEST',
  INSTANCE_SHOW_FAIL = VIEW_NAME + '/INSTANCE_SHOW_FAIL',
  INSTANCE_SHOW_SUCCESS = VIEW_NAME + '/INSTANCE_SHOW_SUCCESS',
  INSTANCE_SHOW_ADJACENT = VIEW_NAME + '/INSTANCE_SHOW_ADJACENT',
  TAB_SELECT = VIEW_NAME + '/TAB_SELECT',
  VIEW_REDIRECT_REQUEST = VIEW_NAME + '/VIEW_REDIRECT_REQUEST',
  VIEW_REDIRECT_FAIL = VIEW_NAME + '/VIEW_REDIRECT_FAIL',
  VIEW_REDIRECT_SUCCESS = VIEW_NAME + '/VIEW_REDIRECT_SUCCESS',
  VIEW_INITIALIZE_REQUEST = VIEW_NAME + '/VIEW_INITIALIZE_REQUEST',
  VIEW_INITIALIZE_FAIL = VIEW_NAME + '/VIEW_INITIALIZE_FAIL',
  VIEW_INITIALIZE_SUCCESS = VIEW_NAME + '/VIEW_INITIALIZE_SUCCESS',
  VIEW_EXIT = VIEW_NAME + '/VIEW_EXIT';
