version: 2
jobs:
  inject-environment:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:1
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: |
            circle_ci_add_env.sh DOCKER_USER DOCKER_PASS OC_EPROC_MACHINEUSER_GITHUB_USERNAME OC_EPROC_MACHINEUSER_GITHUB_TOKEN MAVEN_REPO JFROG_USER JFROG_PASSWD
  release:
    docker:
      - image: opuscapita/minsk-core-release-manager:1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    environment:
      GH_TOKEN: $OC_EPROC_MACHINEUSER_GITHUB_TOKEN
      GH_NAME: $OC_EPROC_MACHINEUSER_GITHUB_USERNAME
    steps:
      - checkout
      - run:
          name: Executing release script
          command: release.sh node
workflows:
  version: 2
  release-and-build:
    jobs:
      - inject-environment
      - release:
          requires:
            - inject-environment
