defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:4
  working_directory: ~/build

version: 2.1

orbs:
  jira: circleci/jira@1.2.2

jobs:
  init:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
    steps:
      - run: circle_ci_add_env.sh GH_MAIL GH_NAME

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    
      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
            - ./yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm run test -- --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./junit/test-results.xml


      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit


  update-gh-pages:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build-gh-pages
          command: ./scripts/gh-pages/build.sh

      - run:
          name: deploy-gh-pages
          command: ./scripts/gh-pages/deploy.sh .gh-pages-tmp

  build_release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    
      - run: if [ -f /.dockerenv ]; then configure-maven.sh && configure-grails.sh && configure-npm.sh; fi

      - run:
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - ./node_modules
            - ./yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: |
            npm run test -- --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./junit/test-results.xml


      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - run:
          name: "Deploy."
          command: npm run publish-release

  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Executing release scrtipt.
          command: .circleci/release.sh

workflows:
  version: 2
  release-and-build:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              only: release
          requires:
            - init
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - release
          requires:
            - init
          post-steps:
            - jira/notify
      - update-gh-pages:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
      - build_release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - init
         post-steps:
            - jira/notify
