version: 2
jobs:
  inject-environment:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:1
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: |
            circle_ci_add_env.sh DOCKER_USER DOCKER_PASS OC_EPROC_MACHINEUSER_GITHUB_USERNAME OC_EPROC_MACHINEUSER_GITHUB_TOKEN
  release:
    docker:
      - image: opuscapita/minsk-core-release-manager:2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Executing release script
          command: release.sh --node --gh-name=${OC_EPROC_MACHINEUSER_GITHUB_USERNAME} --gh-token=${OC_EPROC_MACHINEUSER_GITHUB_TOKEN}
workflows:
  version: 2
  release-and-build:
    jobs:
      - inject-environment
      - release:
          requires:
            - inject-environment
